# Generated by Django 4.0.3 on 2022-08-15 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='pincode',
            field=models.CharField(default=638002, max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]*[0-9][0-9]$', 'enter only numbers')]),
            preserve_default=False,
        ),
    ]
