# Generated by Django 4.1.3 on 2022-11-22 14:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alpha", "0003_remove_warehouse_zipcode_warehouse_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="countrycode",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="pincode",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9][0-9][0-9][0-9][0-9][0-9]$", "enter only numbers"
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="inwarehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("dateandtime", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alpha.warehouse",
                    ),
                ),
            ],
        ),
    ]
